name: BOE Security
favicon: null
layout_spectrum: 0.6159352813847363
typography_spectrum: 0.7701060373801738
title: BOE Security
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74086689-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#78b3dd'
    - '#344654'
    - '#c6e1f2'
    - '#162029'
    - '#e08a5d'
  brandStrength: 0.13274555373936892
  lightness: 0.703429436776787
  saturation: 0.5377942698542029
  rhythmicContrast: 0.0639809041749686
purpose: []
